services:
  presidio-analyzer:
    image: mcr.microsoft.com/presidio-analyzer:2.2.358
    platform: linux/amd64
    ports:
      - "5002:3000"
    restart: unless-stopped

  presidio-anonymizer:
    image: mcr.microsoft.com/presidio-anonymizer:2.2.358
    platform: linux/amd64
    ports:
      - "5001:3000"
    restart: unless-stopped

